Feature/braille 248 add study text
braille-systems/learnbraille_ios pull request #126
Opened 2021-04-23 23:58 UTC by pikabol88

2021-04-24 21:10 UTC, Oleg595 approved these changes

2021-04-25 07:38 UTC, OvechkinDanil requested changes

2021-04-25 07:38 UTC, OvechkinDanil commented on braille_abc/lib/components/lesson_buttons.dart
> +                navigate = true;
Почему здесь 2 раза navigate присваивается значение?

2021-04-25 07:38 UTC, OvechkinDanil commented on braille_abc/lib/components/lesson_section_widget.dart
> +              */
Нужны ли эти комментарии в будущем?

2021-04-25 07:38 UTC, OvechkinDanil commented on braille_abc/lib/models/study_model.dart
> +            } else if (type == "info") {
Возможно стоит эти строки вынести в enum

2021-04-25 07:38 UTC, OvechkinDanil commented on braille_abc/lib/screens/letter_screen.dart
> +
Нужен ли этот закомментированный код в будущем?

2021-04-25 09:43 UTC, pikabol88 commented on braille_abc/lib/components/lesson_section_widget.dart
> +              */
Не стала удалять, так как потом сюда надо будет добавить норм озвучку. Сейчас она отсутствует

2021-04-25 10:01 UTC, pikabol88 commented on braille_abc/lib/screens/letter_screen.dart
> +
Удалила

2021-04-25 10:01 UTC, pikabol88 commented on braille_abc/lib/models/study_model.dart
> +            } else if (type == "info") {
Вынесла

2021-04-25 10:01 UTC, pikabol88 commented on braille_abc/lib/components/lesson_buttons.dart
> +                navigate = true;
Исправлено

2021-04-25 10:11 UTC, ThinkingFrog commented on braille_abc/lib/components/lesson_buttons.dart
> +        width: ScreenParams.width(15, context),
В стили это не нужно вынести?

2021-04-25 10:11 UTC, ThinkingFrog commented on braille_abc/lib/components/letter_buttons.dart
> +            child: BackForthButton(type: lessonButtonType.backward, symbol: super.widget.symbol),
Тоже выглядит как что-то, что можно занести в стили

2021-04-25 11:29 UTC, pikabol88 commented on braille_abc/lib/components/lesson_buttons.dart
> +        width: ScreenParams.width(15, context),
Вынесла

2021-04-25 11:29 UTC, pikabol88 commented on braille_abc/lib/components/letter_buttons.dart
> +            child: BackForthButton(type: lessonButtonType.backward, symbol: super.widget.symbol),
Вынесла

2021-04-25 11:49 UTC, OvechkinDanil approved these changes

2021-04-25 18:02 UTC, ThinkingFrog approved these changes

2021-04-26 13:11 UTC, kirillkuks approved these changes

2021-04-26 13:14 UTC, merged