BRAILLE: Fix hint counter
braille-systems/learnbraille_ios pull request #189
Opened 2021-05-21 13:21 UTC by kirillkuks

2021-05-21 15:59 UTC, ThinkingFrog requested changes

2021-05-21 15:59 UTC, ThinkingFrog commented on braille_abc/pubspec.yaml
> +version: 0.5.2+0
Номер сборки надо +16 поставить

2021-05-21 17:58 UTC, Oleg595 approved these changes

2021-05-22 11:22 UTC, kirillkuks commented on braille_abc/pubspec.yaml
> +version: 0.5.2+0
Поправил

2021-05-23 10:58 UTC, pikabol88 approved these changes

2021-05-23 11:15 UTC, ThinkingFrog approved these changes

2021-05-23 16:05 UTC, merged