Braille 61 feature/symbol
braille-systems/learnbraille_ios pull request #19
Opened 2021-02-28 19:13 UTC by Oleg595

2021-02-28 19:52 UTC, ThinkingFrog commented on braille_abc/lib/symbol/symbol.dart
> +      alignment: Alignment((300.0 - Width) / (2 * 300.0), 0.7),
Всё тот же вопрос откуда такая формула, из каких значений складывается и к чему приводит

2021-02-28 21:01 UTC, Oleg595 commented on braille_abc/lib/symbol/symbol.dart
> +      alignment: Alignment((300.0 - Width) / (2 * 300.0), 0.7),
Да, я это увидел и исправил

2021-03-01 08:12 UTC, pikabol88 requested changes

2021-03-01 08:12 UTC, pikabol88 commented on braille_abc/lib/symbol/symbol.dart
> +),);
Второй main вызовет ошибки, если мы вольем это в основной проект 
Лучше склонировать проект с основной ветки и добавить свой код туда

2021-03-01 11:52 UTC, pikabol88 approved these changes

2021-03-01 11:54 UTC, OvechkinDanil approved these changes

2021-03-01 11:56 UTC, merged