BRAILLE-182 Immutable classes
braille-systems/learnbraille_ios pull request #75
Opened 2021-03-28 18:42 UTC by OvechkinDanil

Add identifiers:
- final 
- const 
- @immutable

2021-03-28 20:14 UTC, pikabol88 requested changes

2021-03-28 20:14 UTC, pikabol88 commented on braille_abc/lib/components/expandable_list_widget.dart
> +          color: CupertinoColors.tertiarySystemBackground,
Это ветка от main? Везде по коду затерся вынес цветов и стилей

2021-03-28 20:14 UTC, pikabol88 commented on braille_abc/lib/components/expansion_section_widget.dart
> +          borderRadius:  BorderRadius.circular(10)),
вот тут был вынос BoxDecoration

2021-03-28 20:15 UTC, pikabol88 requested changes
Слетело все то, то было сделано в ветке вынесения стилей

2021-03-28 20:16 UTC, OvechkinDanil commented on braille_abc/lib/components/expandable_list_widget.dart
> +          color: CupertinoColors.tertiarySystemBackground,
Это ветка от старого main
Надо влить туда main, как-то не заметил этого

2021-03-28 21:34 UTC, pikabol88 approved these changes

2021-03-29 07:25 UTC, derkanw approved these changes

2021-03-29 08:41 UTC, merged